name: test

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

# This allows one Build workflow run to interrupt another
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: show GITHUB_SHA and GITHUB_REF
        run: |
          echo "GITHUB_SHA" ${{ github.sha }}
          echo "GITHUB_REF" ${{ github.ref }}
          sleep 20
      - name: step2
        run: sleep 300
